name: Release

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check version
        # Cargo requires that Cargo.toml contain a version, and that version is
        # used by cargo-deb to build the package. Make sure that the version has
        # been bumped to match the new tag.
        run: |
          gh_tag=$(echo "${{ github.ref }}")
          version=${gh_tag#refs/tags/v}
          echo "Working with version $version"
      - name: Install cargo-deb
        run: cargo install cargo-deb
