name: Release

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    name: Test and publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print something
        run: echo "Hello from ${{ github.ref }}"
